branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

repositoryUrl: https://github.com/petsinc/terraform-provider-telnyx

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
