version: 2

builds:
  - dir: provider
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: freebsd
      - goarch: arm64
        goos: windows
      - goarch: arm64
        goos: openbsd
    binary: 'terraform-provider-telnyx_v{{ .Version }}'

archives:
  - files:
      - src: LICENSE
        dst: LICENSE.txt
    format: zip
    name_template: 'terraform-provider-telnyx_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  algorithm: sha256
  name_template: 'terraform-provider-telnyx_{{ .Version }}_SHA256SUMS'
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: 'terraform-provider-telnyx_{{ .Version }}_manifest.json'

  hooks:
    after:
      - |
        for file in dist/*; do
          if [[ -f "$file" ]]; then
            h1_hash=$(shasum -a 256 "$file" | awk '{print $1}' | xxd -r -p | base64)
            echo "h1:${h1_hash}" >> dist/terraform-provider-telnyx_{{ .Version }}_HASHES.txt
            
            zh_hash=$(shasum -a 256 "$file" | awk '{print $1}')
            echo "zh:${zh_hash}" >> dist/terraform-provider-telnyx_{{ .Version }}_HASHES.txt
          fi
        done

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "{{ .Env.GPG_PASS }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: 'terraform-provider-telnyx_{{ .Version }}_manifest.json'
    - glob: 'dist/terraform-provider-telnyx_{{ .Version }}_HASHES.txt'
      name_template: 'terraform-provider-telnyx_{{ .Version }}_HASHES.txt'
