version: 2

before:
  hooks:
    - (cd provider && go mod tidy)

builds:
  - dir: provider
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: 'terraform-provider-telnyx_v{{ .Version }}'

archives:
  - format: zip
    name_template: 'terraform-provider-telnyx_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: 'terraform-provider-telnyx_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: 'terraform-provider-telnyx_{{ .Version }}_manifest.json'

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "{{ .Env.GPG_PASSPHRASE }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: 'terraform-provider-telnyx_{{ .Version }}_manifest.json'

changelog:
  skip: true
