name: Release

on:
  push:
    branches:
      - main
      - alpha
      - beta

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
      GPG_PASS: ${{ secrets.GPG_PASS }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          # Be sure to keep this in sync with local development .tool-versions
          go-version: "1.22.5"

      - name: Set up GPG
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import

      # - name: Set GPG_TTY
      #   run: |
      #     echo "export GPG_TTY=$(tty)" >> $GITHUB_ENV

      - name: Fetch Dependencies
        working-directory: ./provider/provider
        run: go mod tidy

      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v3

      - uses: goreleaser/goreleaser-action@v4
        if: steps.semantic-release.outputs.new_release_published == 'true'
        with:
          version: "~> v2"
          workdir: ./provider
          args: release
