name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
      GPG_PASS: ${{ secrets.GPG_PASS }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Set up GPG
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import

      # - name: Set GPG_TTY
      #   run: |
      #     echo "export GPG_TTY=$(tty)" >> $GITHUB_ENV

      - name: Change to provider directory and install GoReleaser
        working-directory: provider/provider
        run: |
          curl -sL https://git.io/goreleaser | bash
